table DimDepartment
	lineageTag: 1e0f76fe-6249-4892-b33b-d84b632dde1b

	column DepartmentID
		dataType: string
		lineageTag: 015fa09d-6dd9-490b-ac12-207925c8fd0b
		summarizeBy: none
		sourceColumn: DepartmentID

		annotation SummarizationSetBy = Automatic

	column Department
		dataType: string
		lineageTag: 191818e3-ba01-4024-a484-095f1c28dcd7
		summarizeBy: none
		sourceColumn: Department

		annotation SummarizationSetBy = Automatic

	column Function
		dataType: string
		lineageTag: 1c4f2535-62b8-43fb-8dff-386d31f4518d
		summarizeBy: none
		sourceColumn: Function

		annotation SummarizationSetBy = Automatic

	column CostCenter
		dataType: string
		lineageTag: 99efd686-e1ec-465b-a3e7-a3209a183c36
		summarizeBy: none
		sourceColumn: CostCenter

		annotation SummarizationSetBy = Automatic

	partition DimDepartment = m
		mode: import
		source =
				let
				  Source = Excel.Workbook(File.Contents("C:\Users\Bamzz\Documents\Projects\Data space\HR_Workforce_and_Attrition\HR_Workforce_Planning_Attrition_Dataset_4U_Challenge.xlsx"), null, true),
				  #"Navigation 1" = Source{[Item = "DimDepartment", Kind = "Sheet"]}[Data],
				  #"Changed column type" = Table.TransformColumnTypes(#"Navigation 1", {{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Changed column type", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"DepartmentID", type text}, {"Department", type text}, {"Function", type text}, {"CostCenter", type text}})
				in
				  #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

